/* drv_config.h.  Generated by configure.  */
/* drv_config.h.in.  Generated from configure.in by autoheader.  */

/******************************************************************************

                               Copyright (c) 2005
                            Infineon Technologies AG
                  St. Martin Strasse 53; 81669 Munich, Germany

  THE DELIVERY OF THIS SOFTWARE AS WELL AS THE HEREBY GRANTED NON-EXCLUSIVE,
  WORLDWIDE LICENSE TO USE, COPY, MODIFY, DISTRIBUTE AND SUBLICENSE THIS
  SOFTWARE IS FREE OF CHARGE.

  THE LICENSED SOFTWARE IS PROVIDED "AS IS" AND INFINEON EXPRESSLY DISCLAIMS
  ALL REPRESENTATIONS AND WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING
  WITHOUT LIMITATION, WARRANTIES OR REPRESENTATIONS OF WORKMANSHIP,
  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, DURABILITY, THAT THE
  OPERATING OF THE LICENSED SOFTWARE WILL BE ERROR FREE OR FREE OF ANY THIRD
  PARTY CLAIMS, INCLUDING WITHOUT LIMITATION CLAIMS OF THIRD PARTY INTELLECTUAL
  PROPERTY INFRINGEMENT.

  EXCEPT FOR ANY LIABILITY DUE TO WILLFUL ACTS OR GROSS NEGLIGENCE AND EXCEPT
  FOR ANY PERSONAL INJURY INFINEON SHALL IN NO EVENT BE LIABLE FOR ANY CLAIM
  OR DAMAGES OF ANY KIND, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.

 ******************************************************************************/
#ifndef _DRV_CONFIG_H_
#define _DRV_CONFIG_H_


/* enable debug features as asserts for example */
/* #undef DEBUG */

/* enable trace outputs in general */
#define ENABLE_TRACE 1

/* enable user configuration */
#define ENABLE_USER_CONFIG 1

/* enable evaluation features e.g. for testing with WinEASY */
/* #undef EVALUATION */

/* enabled event logger debugging */
/* #undef EVENT_LOGGER_DEBUG */

/* Name of package */
#define PACKAGE "drv_vinetic"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "VINETIC Device Driver"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "VINETIC Device Driver 1.1.12"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "drv_vinetic"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.1.12"

/* enable runtime traces as register access */
/* #undef RUNTIME_TRACE */

/* enable TAPI Interface */
#define TAPI 1

/* enable TAPI CID support */
#define TAPI_CID 1

/* enable TAPI DTMF support */
#define TAPI_DTMF 1

/* enable TAPI FAX support */
#define TAPI_FAX_T38 1

/* enable TAPI GR909 tests */
/* #undef TAPI_GR909 */

/* enable line testing */
/* #undef TAPI_LT */

/* enable Voice support */
#define TAPI_VOICE 1

/* Version number of package */
#define VERSION "1.1.12"

/* Maximum VINETIC devices to support */
#define VINETIC_MAX_DEVICES 1

/* enable use of proc filesystem entries (Linux only) */
#define VINETIC_USE_PROC 1

/* enable Vinetic 2CPE support */
#define VIN_2CPE 1

/* enable 8 Bit bus access */
/* #undef VIN_8BIT */

/* Vinetic access mode this driver will support */
#define VIN_ACCESS_MODE VIN_ACCESS_MODE_SPI

/* Vinetic access mode string */
#define VIN_ACCESS_MODE_STR "16bit SPI"

/* Vinetic access width this driver will support */
#define VIN_ACCESS_WIDTH VIN_ACCESS_WIDTH_16

/* special option to enable byte swapping inside VINETIC-2CPE */
/* #undef VIN_BYTE_SWAP */

/* configure options string */
#define VIN_CONFIGURE_STR "'--enable-spi' '--enable-2cpe' '--enable-kernelincl=foo' '--with-access-mode=SPI'"

/* enable including default firmware */
/* #undef VIN_DEFAULT_FW */

/* enable SPI interface, needs user configuration */
#define VIN_SPI 1

/* enable Vinetic V1.x support */
#define VIN_V14_SUPPORT 1

/* enable Vinetic V2.x support */
#define VIN_V21_SUPPORT 1


#endif /* _DRV_CONFIG_H_ */

